#
# Basic settings.
#
url: http://tristanburnside.github.io # e.g. http://you.github.io
baseurl: # e.g. /blog
title: Tristan Burnside
description: An iOS developer at Outware Mobile.
avatar: /assets/img/avatar.jpg

#
# Icons
#
icons:
  rss: true
  email: tristan.j.burnside@gmail.com
  github: tristanburnside
  bitbucket:
  twitter:
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: http://www.linkedin.com/profile/preview?vpa=pub&locale= # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: http://stackoverflow.com/users/2737421/tristan-burnside # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: UA-61579545-1 # e.g. UA-000000-01
disqus: tristanburnside

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons: false
ogp:
  image_url: http://localhost:4000/assets/img/ogp.png
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Styles: "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: redcarpet
redcarpet:
  extensions: ["autolink", "hard_wrap", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes"]
highlighter: pygments

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - vendor
